2044746 Provide IP instance support for Solaris 10u4 and later

diff --git a/ipfilter/buildsunos b/ipfilter/buildsunos
--- a/ipfilter/buildsunos
+++ b/ipfilter/buildsunos
@@ -13,13 +13,19 @@ fi
 
 testcc()
 {
+	echo "test $1"
+	echo '' | $1 -E -
 	if echo '' | $1 -E - >/dev/null 2>&1 ; then
 		CC=$1
 		return 0
 	fi
+	echo "$1 fail"
 	return 1
 }
 
+if [ -f /usr/include/sys/neti.h ] ; then
+	INST='-DINSTANCES=1'
+fi
 if [ $rev = 5 ] ; then
 	if [ ! -f /usr/include/sys/neti.h -a ! -d ../pfil ] ; then
 		cat << __EOF__
@@ -60,6 +66,7 @@ __EOF__
 			fi
 		fi
 	else
+		echo "CC=$CC"
 		testcc $CC
 		if [ $? -ne 0 ] ; then
 			case $CC in
@@ -85,14 +92,14 @@ __EOF__
 	case "$CC" in
 	*gcc*)	# gcc
 		XARCH32_i386=""
-		XARCH32_sparc=""
-		XARCH64_sparc="-m64 -mcmodel=medlow"
+		XARCH32_sparc="-fno-dwarf2-indirect-strings"
+		XARCH64_sparc="-m64 -mcmodel=medlow -fno-dwarf2-indirect-strings"
 		XARCH64_i386="-m64 -mcmodel=kernel -mno-red-zone -ffreestanding"
 		;;
 	*)	# Sun C
 		XARCH32_i386="-Xa -xildoff"
-		XARCH32_sparc="-Xa -xildoff -xarch=v8 -xmemalign=8s"
-		XARCH64_sparc="-Xa -xildoff -xarch=v9 -xchip=ultra -xmemalign=8s -xcode=abs32"
+		XARCH32_sparc="-g -Xa -xildoff -xarch=v8 -xmemalign=8s"
+		XARCH64_sparc="-g -Xa -xildoff -xarch=v9 -xchip=ultra -xmemalign=8s -xcode=abs32 -Wc,-Qiselect-regsym=0 -xO3 -D_ASM_INLINES -Xa -xspace -W0,-Lt -errtags=yes -g -Wc,-Qiselect-T1 -xc99=%all -W0,-noglobal -xdebugformat=stabs -xc99=%all -Wd,-xsafe=unboundsym -Wc,-Qassembler-ounrefsym=0 -W2,-xwrap_int -W0,-xglobalstatic -xregs=no%float -xstrconst"
 		XARCH64_i386="$XARCH32 -xarch=amd64 -xcode=abs32"
 		;;
 	esac
@@ -137,7 +144,7 @@ __EOF__
 		int main(void)
 		{
 			printf("%ld\n", (long) sizeof(long));
-			exit(0);
+			return(0);
 		}
 		EOF
 
@@ -148,6 +155,9 @@ __EOF__
 			echo $CC $XARCH32 cannot create 32 bit executables. 1>&2
 			exit 1
 		fi
+echo "$CC $XARCH64 $t"
+$CC $XARCH64 $t
+file 64.out
 		if $CC $XARCH64 $t -o 64.out >/dev/null 2>&1 &&
 		    { out64=`./64.out 2>/dev/null` ;
 		    [ "$out64" = 8 -o "`isainfo -b`" = 32 -a "$out64" = "" ]
@@ -164,6 +174,7 @@ __EOF__
 
 	# If we're running 64 bit, we *must* build 64 bit.
 	if ([ "`isainfo -b`" = 64 ]) 2>/dev/null ; then
+echo "CC64=${CC64}"
 		if $CC64 ; then :; else
 			echo "No 64 bit capable compiler was found" 1>&2
 			exit 1
@@ -204,5 +215,5 @@ do
     if [ -n "$BPFILTER" ] ; then
 	BPF="BPFILTER=$OBJ/$BPFILTER"
     fi
-    $MAKE $MAKEFLAGS ${1+"$@"} sunos$rev SOLARIS2="-DSOLARIS2=$solrev" CPU= CPUDIR=${cpudir} CC="$CC $XARCH" XARCH="$XARCH" ARCHINC="$ARCHINC" BITS=$b OBJ=$OBJ $BPF || exit $?
+    $MAKE $MAKEFLAGS ${1+"$@"} sunos$rev SOLARIS2="-DSOLARIS2=$solrev" CPU= CPUDIR=${cpudir} CC="$CC $XARCH" XARCH="$XARCH" INSTANCE="$INST" ARCHINC="$ARCHINC" BITS=$b OBJ=$OBJ $BPF || exit $?
 done
